apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: site1
  namespace: default
spec:
  interval: 10m
  # targetNamespace: default
  bases:
  - ../base
  patchesStrategicMerge:
  - linux-ubuntu-vm.yaml.yaml

